version: "3.9"

services:
    web:
        build:
            context: .
        image: nginx:latest
        restart: always
        networks:
            app_net:
                ipv4_address: 172.20.3.10
        ports:
            - "8080:80"
        volumes:
            - .:/wwwroot/
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:8.1-fpm
        restart: always
        volumes:
            - .:/wwwroot/
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            app_net:
                ipv4_address: 172.20.3.20
    redis:
        image: redis:latest
        restart: always
        ports:
            - "26379:6379"
        networks:
            app_net:
                ipv4_address: 172.20.3.30
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'fucking123sql'
        ports:
            - "23306:3306"
        networks:
            app_net:
                ipv4_address: 172.20.3.40

networks:
    app_net:
        ipam:
            driver: default
            config:
                -   subnet: 172.20.3.0/24
